### ISSUE TITLE
[REQUEST] Links to required dependencies

### ISSUE THREAD

**Issue by mgxd** [NIRALUser/NeosegPipeline#17]
Looking through the executables.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Neoseg-pipeline-executables>
<Tools-Paths>
    <Executables>
        <python path="/Users/mathiasg/.pyenv/shims/python"/>
        <SegPostProcessCLP path=""/>
        <N4ITKBiasFieldCorrection path=""/>
        <ANTS path=""/>
        <ITKTransformTools path=""/>
        <dtiestim path=""/>
        <dtiprocess path=""/>
        <bet2 path=""/>
        <SpreadFA path=""/>
        <unu path=""/>
        <ResampleScalarVectorDWIVolume path=""/>
        <ImageMath path=""/>
        <WeightedLabelsAverage path=""/>
        <neoseg path=""/>
        <ReassignWhiteMatter path=""/>
        <InsightSNAP path=""/>
        <ABC path=""/>
        <antsJointFusion path=""/>
    </Executables>
    <Library-directories>
        <FSL path=""/>
    </Library-directories>
</Tools-Paths>
```
there are a few required executables that I'm not instantly familiar with - is there a more comprehensive list with information on each required executable?

**Comment by juanprietob** [comment]
If you are trying to compile the tool, I suggest enabling the Superbuild feature. All the required executables will be built. 
If you are trying to run the tool, you can download the precompiled binaries. We have them for Mac and Linux. The precompiled binaries are in the release section -> https://github.com/NIRALUser/NeosegPipeline/releases

**Comment by mgxd** [comment]
Thanks! I couldn't find them in the Mac release, but do see them in the Linux one. Some further questions:
- Will I need to download FSL / `bet2` separately? since I don't see them in the precompiled binaries
- Is there interest in having a Docker recipe / container? If so, I can send in a PR.

**Comment by mgxd** [comment]
Since the releases come bundled with the dependencies, I'll close this issue.
