### ISSUE TITLE
WeightedLabelsAverage intolerant to small differences in origin

### ISSUE THREAD

**Issue by styner** [NIRALUser/NeosegPipeline#5]
WeightedLabelsAverage is very sensitive to small differences in origin. Neosegpipeline adapts the origin to be the same, but does so AFTER calling WeightedLabelsAverage. I suggest to invert that order and first ensure that all origins are the same before calling WeightedLabelsAverage

**Comment by juanprietob** [comment]
This is solved in latest release.
